# ecs.yml
services:
  Symplify\CodingStandard\Sniffs\CleanCode\CognitiveComplexitySniff:
    maxCognitiveComplexity: 8
  Wunderio\CodingStandards\Finder\DrupalFileFinder: ~
  Wunderio\CodingStandards\Sniffs\Debug\KintFunctionCallSniff: ~
